
USE  college
 

CREATE TABLE NewAdmission(
NAID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
fname VARCHAR (250) NOT NULL,
mname VARCHAR(250) NOT NULL,
gender VARCHAR(10)NOT NULL,
dob VARCHAR (50) NOT NULL,
mobile BIGINT NOT NULL,
email VARCHAR (150) NOT NULL,
semester VARCHAR (100) NOT NULL,
prog VARCHAR (150) NOT NULL,
sname VARCHAR (150) NOT NULL,
duration VARCHAR (120) NOT NULL,
addres VARCHAR(250) NOT NULL
);

SELECT * FROM NewAdmission;

 


